### ISSUE TITLE
Atari Result Summary Figure

### ISSUE THREAD

**Issue by liziniu** [deepmind/dqn_zoo#12]
Hi,

First, thanks for sharing the results.tar.gz.

I am interested in the summary figure provided. However, I cannot exactly reproduce the curves with the given CSV files. My implementation is as follows: for each algorithm (e.g., DQN)，
1.  Compute the mean of **normalized return** over 5 random seeds for each environment.
2.  Plot the solid line with the median and the shaded region with maximal and minimal values over 57 environments using the results from Step 1.

I can basically reproduce the solid lines but the shaded region is not expected.

Your clarification would be very helpful!

Thanks 
Ziniu

**Comment by jqdm** [comment]
Thanks for your interest.

That is one way to generate a similar plot. The method used for the summary plot in the `README.md` was chosen so that it roughly follows the one in the Rainbow paper, but for multiple seeds.

To generate the summary plot, the data was first smoothed with a moving average with window of size `10` as mentioned in the `README.md`. Given an agent, frame and seed, the median normalized return over environment is calculated. Then the DataFrame was passed to `seaborn.lineplot()` with `estimator=numpy.median` and `ci=100`, so the shaded area captures the variation over seeds.

If that's not clear, a Colab notebook showing how the summary plot was generated will be uploaded soon.

**Comment by jqdm** [comment]
Added Colab notebook for generating plots in 98bd61d0b27f57a4f9cacc87002285ecf5d4c09e.
