### ISSUE TITLE
Is the AtariEnvironmentWrapper not being used?

### ISSUE THREAD

**Issue by raymondchua** [deepmind/dqn_zoo#19]
Hi, 
Is this function being used anywhere?

**Comment by jqdm** [comment]
Thanks for your interest, indeed `AtariEnvironmentWrapper` is not used anywhere. It was originally used during development of these agents to make it easier to compare having the Atari preprocessing in the environment versus in the agent itself. We eventually went with having the preprocessing in the agent for a number of reasons, but since it is more common to have the preprocessing in the environment, `AtariEnvironmentWrapper` was kept for the convenience of users.

**Comment by raymondchua** [comment]
I see. Thanks for your reply, John :)
